
[[NamedAnchors]]
Name = '''data.header.romname'''
Address = 0x000108
Format = '''`asc`32'''

[[OffsetPointer]]
Address = 0x038850
Offset = 0x000004

[[OffsetPointer]]
Address = 0x0389F8
Offset = 0x000004

[[OffsetPointer]]
Address = 0x069188
Offset = 0x000004

[[OffsetPointer]]
Address = 0x069230
Offset = 0x000004

[[OffsetPointer]]
Address = 0x06B82C
Offset = 0x000004

[[List]]
Name = '''pokenavTowns'''
0 = [
   '''LITTLEROOT TOWN''',
   '''OLDALE TOWN''',
   '''DEWFORD TOWN''',
   '''LAVARIDGE TOWN''',
   '''FALLARBOR TOWN''',
   '''VERDANTURF TOWN''',
   '''PACIFIDLOG TOWN''',
   '''PETALBURG CITY''',
   '''SLATEPORT CITY TOP''',
   '''SLATEPORT CITY BOTTOM''',
   '''MAUVILLE CITY LEFT''',
   '''MAUVILLE CITY RIGHT''',
   '''RUSTBORO CITY TOP''',
   '''RUSTBORO CITY BOTTOM''',
   '''FORTREE CITY''',
   '''LILYCOVE CITY LEFT''',
   '''LILYCOVE CITY RIGHT''',
   '''MOSSDEEP CITY LEFT''',
   '''MOSSDEEP CITY RIGHT''',
   '''SOOTOPOLIS CITY''',
   '''EVER GRANDE CITY TOP''',
   '''EVER GRANDE CITY BOTTOM''',
]

[[GotoShortcut]]
Name = '''Pokemon'''
Image = '''graphics.pokemon.sprites.front/295/sprite/'''
Destination = '''data.pokemon.stats/1'''

[[GotoShortcut]]
Name = '''Trainers'''
Image = '''graphics.trainers.sprites.front/3/sprite/'''
Destination = '''data.trainers.stats'''

[[GotoShortcut]]
Name = '''Moves'''
Image = '''graphics.items.sprites/298/sprite/'''
Destination = '''data.pokemon.moves.stats.battle'''

[[GotoShortcut]]
Name = '''Items'''
Image = '''graphics.items.sprites/13/sprite/'''
Destination = '''data.items.stats'''
