








# https://github.com/pret/pokeemerald/blob/cd895e497d68bf9adbaa067dc411cc99a3bd1a4b/src/pokemon.c
# CreateBoxMon
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x03A8A2
Length = 1
Offset = -1

# https://github.com/pret/pokeemerald/blob/cd895e497d68bf9adbaa067dc411cc99a3bd1a4b/src/pokemon.c
# GetMonSpritePalFromSpeciesAndPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x040988
Length = 1
Offset = -1

# https://github.com/pret/pokeemerald/blob/cd895e497d68bf9adbaa067dc411cc99a3bd1a4b/src/pokemon.c
# GetMonSpritePalStructFromOtIdPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x0409FE
Length = 1
Offset = -1

# https://github.com/pret/pokeemerald/blob/cd895e497d68bf9adbaa067dc411cc99a3bd1a4b/src/pokemon.c
# IsShinyOtIdPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x040D14
Length = 1
Offset = -1

















# https://github.com/pret/pokeemerald/blob/51cd0ac08116674a8ebd258af0620c2f7de9dc0e/src/battle_anim_special.c
# sub_8172EF0
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x14189A
Length = 1
Offset = -1
