








# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# CreateBoxMon
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x03DB5E
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# GetMonSpritePalFromSpeciesAndPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x044120
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# GetMonSpritePalStructFromOtIdPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x044196
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# IsShinyOtIdPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x0444B0
Length = 1
Offset = -1


# apparently used for pokedex pokemon palette choosing, although I can't find the function in pokefirered
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x104A24
Length = 1
Offset = 0









# https://github.com/pret/pokefirered/blob/4cf09577950db22d7f0acf6ede45b8dca1c97156/src/battle_anim_special.c
# sub_80F1720
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x0F1776
Length = 1
Offset = -1

##################################################################### scripts.pokedex.regional.length (originally 151 in FireRed)

# https://github.com/pret/pokefirered/blob/f1d821ecc28d8355b83fae6f0a2a890992c6929f/src/pokedex.c
# GetKantoPokedexCount
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x088F18
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/f1d821ecc28d8355b83fae6f0a2a890992c6929f/src/pokedex.c
# HasAllKantoMons
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x088F76
Length = 1
Offset = -2

# https://github.com/pret/pokefirered/blob/83806d0f95f9298bfa6d8775f5ea79a8204cc910/src/pokedex_screen.c
# sub_8103518
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x10352C
Length = 1
Offset = 0

# https://github.com/pret/pokefirered/blob/83806d0f95f9298bfa6d8775f5ea79a8204cc910/src/pokedex_screen.c
# sub_8103518
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x1035F6
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/83806d0f95f9298bfa6d8775f5ea79a8204cc910/src/pokedex_screen.c
# sub_8104BBC
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x104BF2
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/4cf09577950db22d7f0acf6ede45b8dca1c97156/src/party_menu.c
# MonCanEvolve
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x126C4A
Length = 1
Offset = 0

##################################################################### scripts.daycare.exp.multiplier
# https://github.com/pret/pokefirered/blob/4cf09577950db22d7f0acf6ede45b8dca1c97156/src/daycare.c
# TryProduceOrHatchEgg
[[MatchedWords]]
Name = '''scripts.daycare.exp.multiplier'''
Address = 0x0462E8
Length = 1
Offset = 0
Note = '''Picking an even number will prevent new eggs from being created.'''
# ShouldEggHatch
[[MatchedWords]]
Name = '''scripts.daycare.exp.multiplier'''
Address = 0x0463D4
Length = 1
Offset = 0
Note = '''Picking an even number will prevent new eggs from being created.'''

