








# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# CreateBoxMon
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x03DB5E
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# GetMonSpritePalFromSpeciesAndPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x044120
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# GetMonSpritePalStructFromOtIdPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x044196
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/6001e107993d1da69decdf479abf8a661ad57dda/src/pokemon.c
# IsShinyOtIdPersonality
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x0444B0
Length = 1
Offset = -1


# apparently used for pokedex pokemon palette choosing, although I can't find the function in pokefirered
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x1049FC
Length = 1
Offset = 0









# https://github.com/pret/pokefirered/blob/4cf09577950db22d7f0acf6ede45b8dca1c97156/src/battle_anim_special.c
# sub_80F1720
[[MatchedWords]]
Name = '''scripts.shiny.odds'''
Address = 0x0F174E
Length = 1
Offset = -1

##################################################################### scripts.pokedex.regional.length (originally 151 in FireRed)

# https://github.com/pret/pokefirered/blob/f1d821ecc28d8355b83fae6f0a2a890992c6929f/src/pokedex.c
# GetKantoPokedexCount
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x088EEC
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/f1d821ecc28d8355b83fae6f0a2a890992c6929f/src/pokedex.c
# HasAllKantoMons
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x088F4A
Length = 1
Offset = -2

# https://github.com/pret/pokefirered/blob/83806d0f95f9298bfa6d8775f5ea79a8204cc910/src/pokedex_screen.c
# sub_8103518
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x103504
Length = 1
Offset = 0

# https://github.com/pret/pokefirered/blob/83806d0f95f9298bfa6d8775f5ea79a8204cc910/src/pokedex_screen.c
# sub_8103518
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x1035CE
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/83806d0f95f9298bfa6d8775f5ea79a8204cc910/src/pokedex_screen.c
# sub_8104BBC
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x104BCA
Length = 1
Offset = -1

# https://github.com/pret/pokefirered/blob/4cf09577950db22d7f0acf6ede45b8dca1c97156/src/party_menu.c
# MonCanEvolve
[[MatchedWords]]
Name = '''scripts.pokedex.regional.length'''
Address = 0x126C22
Length = 1
Offset = 0

##################################################################### scripts.daycare.exp.multiplier
# https://github.com/pret/pokefirered/blob/4cf09577950db22d7f0acf6ede45b8dca1c97156/src/daycare.c
# TryProduceOrHatchEgg
[[MatchedWords]]
Name = '''scripts.daycare.exp.multiplier'''
Address = 0x0462E8
Length = 1
Offset = 0
Note = '''Picking an even number will prevent new eggs from being created.'''
# ShouldEggHatch
[[MatchedWords]]
Name = '''scripts.daycare.exp.multiplier'''
Address = 0x0463D4
Length = 1
Offset = 0
Note = '''Picking an even number will prevent new eggs from being created.'''

###################################################### graphics.townmap.position.cancel.x / y (21/13)
# place #1: PlaySEForSelectedMapsec
# C04CA is cmp r0, #CANCEL_BUTTON_X
# C04D6 is cmp r0, #CANCEL_BUTTON_Y
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.x'''
Address = 0x0C049E
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.y'''
Address = 0x0C04AA
Length = 1

# place #2: Task_RegionMap
# C06E4 is cmp r0, #CANCEL_BUTTON_X
# C06F0 is cmp r0, #CANCEL_BUTTON_Y
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.x'''
Address = 0x0C06B8
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.y'''
Address = 0x0C06C4
Length = 1

# place #3: HandleRegionMapInput
# C3284 is .word CANCEL_BUTTON_X | (CANCEL_BUTTON_Y << 16) (can be treated as two separate halfwords too, but that's how the compiler put it :P)
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.x'''
Address = 0x0C3258
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.y'''
Address = 0x0C325A
Length = 1

# place #4: SnapToIconOrButton
# C34BC is movs r0, #CANCEL_BUTTON_X
# C34B8 is movs r0, #CANCEL_BUTTON_Y
# (even though cancel constants show up twice in the C, they're only present at one offset in the assembly)
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.x'''
Address = 0x0C3490
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.y'''
Address = 0x0C348C
Length = 1

# place #5: Task_FlyMap
# C50A2 is cmp r0, #CANCEL_BUTTON_X
# C50AE is cmp r0, #CANCEL_BUTTON_Y
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.x'''
Address = 0x0C5076
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.cancel.y'''
Address = 0x0C5082
Length = 1


###################################################### graphics.townmap.position.switch.x / y (21/11)
# place #1: PlaySEForSelectedMapsec
# C049C is cmp r0, #SWITCH_BUTTON_X
# C04A8 is cmp r0, #SWITCH_BUTTON_Y
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.x'''
Address = 0x0C0470
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.y'''
Address = 0x0C047C
Length = 1

# place #2: Task_RegionMap
# C06B0 is the X one
# C06BC is the Y one
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.x'''
Address = 0x0C0684
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.y'''
Address = 0x0C0690
Length = 1

# place #3: HandleRegionMapInput
# C3288 is .word X | (Y << 16)
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.x'''
Address = 0x0C325C
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.y'''
Address = 0x0C325E
Length = 1

# place #4: SnapToIconOrButton
# C3478 is the X one
# C347C is the Y one
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.x'''
Address = 0x0C344C
Length = 1
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.y'''
Address = 0x0C3450
Length = 1

# place #5: the drawing part in BufferRegionMapBg
# not sure exactly how the math works out, but there are X and Y values here that
# are somewhat related to SWITCH_BUTTON_X/Y. hopefully the cursor moves based on tiles
# and this is just a simple + 3 or + 4 to the constants
# C0D52 is mov r2, #24  (x+3)
# C0D54 is mov r3, #14  (y+3)
# C0D68 is mov r2, #24  (x+3)
# C0D6A is mov r3, #15  (y+4)
# C0D7E is mov r2, #24  (x+3)
# C0D80 is mov r3, #16  (y+5)
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.x'''
Address = 0x0C0D26
Length = 1
Offset = 3
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.y'''
Address = 0x0C0D28
Length = 1
Offset = 3
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.x'''
Address = 0x0C0D3C
Length = 1
Offset = 3
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.y'''
Address = 0x0C0D3E
Length = 1
Offset = 4
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.x'''
Address = 0x0C0D52
Length = 1
Offset = 3
[[MatchedWords]]
Name = '''graphics.townmap.position.switch.y'''
Address = 0x0C0D54
Length = 1
Offset = 5
